pr:
  branches:
    include:
    - dev

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: MSBuild@1
    name: 'Swagger_to_SDK_build'
    inputs:
      msbuildArguments: /t:StartNetSdkCodeGeneration /v:n /p:githubprnumber=$(System.PullRequest.PullRequestNumber) /p:githubcommitid=$(something) /p:giturl=$(System.PullRequest.SourceRepositoryURI) /p:DebugMode=false /p:triggercomment=""
      solution: scripts\stostools\SToS.proj
