pr:
  branches:
    include:
    - dev

pool:
  vmImage: 'VS2017-Win2016'

variables:
  TriggerComment: "Dummy comment will be removed"
  SwagToSdkGenArgs: /t:StartNetSdkCodeGeneration /v:n /p:githubprnumber=$(System.PullRequest.PullRequestNumber) /p:githubcommitid=$(Build.SourceVersion) /p:giturl=$(System.PullRequest.SourceRepositoryURI) /p:DebugMode=false /p:triggercomment=$(TriggerComment)

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - script: npm install autorest -g
    displayName: Install autorest

  - task: MSBuild@1
    name: 'Swagger_to_SDK_build'
    inputs:
      msbuildArguments: $(SwagToSdkGenArgs)
      solution: scripts\stostools\SToS.proj
