pr:
  branches:
    include:
    - dev

jobs:
- job: "DotNetSdk"
  variables:
    NODE_OPTIONS: '--max-old-space-size=8192'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - task: CmdLine@1
  - script: scripts\stostools\LaunchSToS.bat scripts\stostools\SToS.proj %ghprbPullId% %ghprbActualCommit% %GIT_URL% %CustomComment% false n
    displayName: '.NET Sdk PR Automation job'