pr:
  branches:
    include:
    - dev

pool:
  vmImage: 'VS2017-Win2016'

steps:

 - task: CmdLine@1
   inputs:
     filename: scripts\stostools\LaunchSToS.bat
     arguments: scripts\stostools\stos.proj %SYSTEM_PULLREQUEST_PULLREQUESTNUMBER% %SYSTEM_PULLREQUEST_SOURCECOMMITID% %SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI% %CustomComment% false n